spring:
  application:
    name: msvc-companies
  config:
    import: optional:configserver:http://localhost:7777
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      connection-timeout: ${db.connection-timeout}
      maximum-pool-size: ${db.maximum-pool-size}
  devtools:
    restart:
      enabled: true
      poll-interval: 500
      quiet-period: 100
      additional-paths: src/main/java
      exclude: static/**,public/**,resources/**
    livereload:
      enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/