spring:
  application:
    name: msvc-companies
  config:
    import: optional:configserver:http://localhost:7777
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      connection-timeout: ${db.connection-timeout:20000}
      maximum-pool-size: ${db.maximum-pool-size:5}
  devtools:
    restart:
      enabled: true
      poll-interval: 500
      quiet-period: 100
      additional-paths: src/main/java
      exclude: static/**,public/**,resources/**
    livereload:
      enabled: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  servlet:
    context-path: /msvc-companies
  port:
  # Observabilidad
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
  metrics:
    distribution:
      percentiles:
        do.sleep.method.timed: 0.99, 0.95, 0.9, 0.7, 0.5
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        do.sleep.method.timed: true
        http.server.requests: true
      minimum-expected-value:
        do.sleep.method.timed: 100ms
        http.server.requests: 100ms
      maximum-expected-value:
        do.sleep.method.timed: 10s
        http.server.requests: 10s
      slo:
        do.sleep.method.timed: 300ms,500ms,1s,2s
        http.server.requests: 300ms,500ms,1s,2s
  # Permitir que todo los endponts genere metricas
  endpoints:
    web:
      exposure:
        include: '*'