spring:
  application:
    name: msvc-report-listener
  config:
    import: optional:configserver:http://localhost:7777
  profiles:
    default: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      function:
        bindings:
          #Relaciones de entrada y salidas
          # consumerReport-out -> consumer report <- consumerReport-in
          consumerReport-in-0:
            destination: consumerReport
  data:
    mongodb:
      database: sa
      username: sa
      authentication-database: admin
      host: localhost
      port: 27017
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9093