spring:
  application:
    name: gateway
  profiles:
    default: default
server:
  port: 9292
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true