spring:
  application:
    name: gateway
  profiles:
    default: eureka-on
server:
  port: 9292
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
#  instance:
#    instance-id: "${spring.application.name}:${random.value}"