#name: Build and Push to GHCR
#
#on:
#  push:
#    branches: [main]
#    tags: ['v*']
#
#jobs:
#  build-and-push:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
##          username: ${{ github.actor }}
##          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and push images
#        run: |
#
#          docker build -t ghcr.io/raydberg/eureka-server:latest ./eureka-server
#          docker build -t ghcr.io/raydberg/config-server:latest ./config-server
#          docker build -t ghcr.io/raydberg/gateway:latest ./gateway
#          docker build -t ghcr.io/raydberg/msvc-companies:latest ./msvc-companies
#          docker build -t ghcr.io/raydberg/msvc-security:latest ./msvc-security
#
#          docker push ghcr.io/raydberg/eureka-server:latest
#          docker push ghcr.io/raydberg/config-server:latest
#          docker push ghcr.io/raydberg/gateway:latest
#          docker push ghcr.io/raydberg/msvc-companies:latest
#          docker push ghcr.io/raydberg/msvc-security:latest