spring:
  application:
    name: msvc-report-ms
  config:
    import: optional:configserver:http://localhost:7777
  devtools:
    restart:
      enabled: true
      poll-interval: 500
      quiet-period: 100
      additional-paths: src/main/java
      exclude: static/**,public/**,resources/**
    livereload:
      enabled: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      function:
        bindings:
          #Relaciones de entrada y salidas
          consumerReport-out-0:
            destination: consumerReport
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  servlet:
    context-path: /msvc-report-ms
  port: 9094